### ISSUE TITLE
Incompatibility with Overcharged Main Menu mod

### ISSUE THREAD

**Issue by FRBFStudios** [SorkoPiko/DailyStreak#1]
I am using the "Overcharged Main Menu"-mod and the streak counter doesn't show up, could you please fix this?

**Comment by SorkoPiko** [comment]
i'll look into it, thanks!

**Comment by SorkoPiko** [comment]
Fixed in v1.1.0

**Comment by Hanifinio** [comment]
Where do I find the streak? (Or does it only appear on 2nd day)

**Comment by FRBFStudios** [comment]
it should be a small text above the daily level box (you need to click the daily level button in the create tab in case you don't use overcharged main menu)
