### ISSUE TITLE
Can you add a badge?

### ISSUE THREAD

**Issue by darvin-exe** [SorkoPiko/DailyStreak#2]
If you don't mind, could you add an option that adds a badge on the button with the daily and weekly levels, like on mod logo? (preview in screenshot)
![badge_idea](https://github.com/user-attachments/assets/404d97db-db48-4600-8da0-715826bae030)

**Comment by SorkoPiko** [comment]
i was thinking about it, but it would be hard to implement as really long numbers wouldn't fit. plus, there's no real need imo. if you wanna talk about it further join the discord server (in the readme)
