### ISSUE TITLE
(Android64) The streak showed 1 when it should be 5

### ISSUE THREAD

**Issue by Hanifinio** [SorkoPiko/DailyStreak#3]
I just glanced at the streak today and it said 1. I've beaten every daily since 5 days ago while having the mod installed. Images below 
![Screenshot_20240821_181505_Geode](https://github.com/user-attachments/assets/74229d90-a132-49ed-a2cb-657c4345efd9)
![Screenshot_20240821_181513_Geode](https://github.com/user-attachments/assets/097d65c5-9f7a-43d0-ade7-6695a8cd4381)

**Comment by Hanifinio** [comment]
If you're wondering what the first image is, it's BetterInfo. It includes a feature allowing you to see what you did on previous daily levels. You can see 100% on 5 levels on the screenshot. 
I included (Android64) in the title incase that's helpful

**Comment by SorkoPiko** [comment]
That's really strange. It should be calculating from your save data, just like BetterInfo.

**Comment by Hanifinio** [comment]
If that's the case then there has to be no way.

**Comment by SorkoPiko** [comment]
what

**Comment by Hanifinio** [comment]
Nothing, just confirming what you said

**Comment by SorkoPiko** [comment]
oh yeah obviously your streak is low, you missed a level (as indicated by the ids). its not showing in betterinfo because you didnt even download it.
![360015876-74229d90-a132-49ed-a2cb-657c4345efd9](https://github.com/user-attachments/assets/6240b1e3-5be4-4437-bbb6-12d4542b44f9)

**Comment by Hanifinio** [comment]
Aaa ok never noticed that number. But I literally do not remember missing anything and I wouldn't do it for 3 stars

**Comment by SorkoPiko** [comment]
you missed this bro
![image](https://github.com/user-attachments/assets/fcb55938-0b98-4344-9da8-b33aa02fd3ed)

**Comment by Hanifinio** [comment]
Thanks for telling cus now I know what happened. I DID beat that level (I went on that just now and I recognise it) so I probably had a crash a bit after (which makes your really recent progress not save). D:
